apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: odh-ml-pipelines-artifact-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: odh-ml-pipelines-artifact-manager
    app.kubernetes.io/part-of: datasciencepipelines
  name: odh-ml-pipelines-artifact-manager
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    app: go-app
    app.kubernetes.io/instance: odh-ml-pipelines-artifact-manager
status:
  loadBalancer: {}
