apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: odh-ml-pipelines-persistenceagent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: odh-ml-pipelines-persistenceagent
    app.kubernetes.io/part-of: datasciencepipelines
  name: odh-ml-pipelines-persistenceagent
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: odh-ml-pipelines-persistenceagent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: odh-ml-pipelines-persistenceagent
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/datasciencepipelines/odh-ml-pipelines-persistenceagent@sha256:5d4fd699f31ca24e7400dea449ae71e784703156949e0306d93f39ec823d9d20
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8888
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
