apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: odh-data-science-pipelines-operator-controller
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/datasciencepipelines/odh-data-science-pipelines-operator-controller@sha256:955433df0ab6be06f0c0c1a975223389a268908129d1ff0caa2b0c4c3ba2e731
        name: container-image
        resources: {}
status: {}
