apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: odh-data-science-pipelines-operator-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: odh-data-science-pipelines-operator-controller
    app.kubernetes.io/part-of: datasciencepipelines
  name: odh-data-science-pipelinerefo
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: odh-data-science-pipelines-operator-controller
    weight: 100
status: {}
