apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: odh-ml-pipelines-cache
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: odh-ml-pipelines-cache
    app.kubernetes.io/part-of: datasciencepipelines
  name: odh-ml-pipelines-cachettbk
spec:
  path: /
  port:
    targetPort: 8888
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: odh-ml-pipelines-cache
    weight: null
status: {}
